discord:
  token: ""
  whitelist-request-channel-id: ""
  whitelist-request-recieve-channel-id: ""
  guild-id: ""
game:
  speedrunerSlots: 20

# data
data:
  whitelist-requests:
    - ""
  linked:
    steve:
      discord: "steve :)"
      type: "speedrun"
  speedrunersLeft: 20
